### ISSUE TITLE
Comparison with existing similar packages

### ISSUE THREAD

**Issue by dandv** [zaki-yama/typescript-npm-package-template#2]
Hi, how is this package different from the much more popular https://github.com/bitjson/typescript-starter? Would help to add that to the README.

**Comment by zaki-yama** [comment]
@dandv 
Thank you for the comment.
I didn't know that repository. As far as I looked a little, that repository doesn't seem to support UMD.

How did you find my repo? That could be help to determine what I should write on README

**Comment by dandv** [comment]
https://github.com/jaredpalmer/tsdx supprts UMD.

How I found your repo? By searching google for "Github typescript package". I guess you've done the same before starting yet another similar project, but didn't find anything back then?

The problem with so many packages doing the same thing, is that people have a hard time choosing among them, and each package is likely to repeat the mistakes of the previous ones.

**Comment by zaki-yama** [comment]
@dandv 
Thanks.

The reason why I created this project is to understand how to configure webpack and TypeScript so that I can build a npm package that supports multiple module formats.
I didn't mean to just "use" the existing project.

I agree with the problem you pointed.
If you notice any mistakes in this repository, I really appreciate if you give me feedbacks.

**Comment by zaki-yama** [comment]
@dandv 
I'll close this issue, but any feedbacks are welcome.
